language: cpp

notifications:
  email: false

sudo: false

os:
  - linux
  - osx

compiler:
  - clang
  - g++-4.9

matrix:
  include:
    - os: osx
      compiler: clang
      env: ANALYZE=true
    - os: linux
      compiler: g++-4.9
      env: COVERALLS=true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - valgrind
      - g++-4.9

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; brew install -v valgrind; fi
  - export SCAN_BUILD=""; export COVERAGE=""; export LCOV=""
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$ANALYZE" = "true" ]; then brew update; brew install -v llvm37; export SCAN_BUILD=scan-build-3.7; fi
  - if [ "$COVERALLS" = "true" ]; then pip install --user cpp-coveralls; export COVERAGE=--coverage; export LCOV="-lgcov"; fi

script:
  - $SCAN_BUILD make CXXFLAGS="-g $COVERAGE"
  - $SCAN_BUILD make build-test CXXFLAGS="-g $COVERAGE" CFLAGS="$COVERAGE" LDLIBS="$LCOV"
  - valgrind --error-exitcode=1 ./test.bin
  - if [ "$COVERALLS" = "true" ]; then coveralls --exclude "test.cpp" --gcov-options '\-lp'; fi
